# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.2
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: true
codecov: true
