name = "Traits"
uuid = "76f64fd0-be06-4389-a21e-5e0dc9b4fa46"
authors = ["Raphael LaFrance"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
